// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuOFy1XVv3GTiyGtFZ4YOq3bUwcjbSHyA',
    appId: '1:156251535423:web:f0c6265eb30d141989608a',
    messagingSenderId: '156251535423',
    projectId: 'notes-af833',
    authDomain: 'notes-af833.firebaseapp.com',
    storageBucket: 'notes-af833.appspot.com',
    measurementId: 'G-ZP334LQRJQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA268p71zNBxH-yP_DpXb_VA_zno_3A_x8',
    appId: '1:156251535423:android:e481883c09553d1a89608a',
    messagingSenderId: '156251535423',
    projectId: 'notes-af833',
    storageBucket: 'notes-af833.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAotYY_15jjnJplQOmyTqb7h7N9Wb4SZNY',
    appId: '1:156251535423:ios:20d6f80c7d5c535489608a',
    messagingSenderId: '156251535423',
    projectId: 'notes-af833',
    storageBucket: 'notes-af833.appspot.com',
    iosClientId: '156251535423-jm91qktrpdn56hgl2q881h3is2n0g8f8.apps.googleusercontent.com',
    iosBundleId: 'dev.amineabeid.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAotYY_15jjnJplQOmyTqb7h7N9Wb4SZNY',
    appId: '1:156251535423:ios:20d6f80c7d5c535489608a',
    messagingSenderId: '156251535423',
    projectId: 'notes-af833',
    storageBucket: 'notes-af833.appspot.com',
    iosClientId: '156251535423-jm91qktrpdn56hgl2q881h3is2n0g8f8.apps.googleusercontent.com',
    iosBundleId: 'dev.amineabeid.notes',
  );
}
